export const MainSideData = [
  {
    firstTitle: "10-Сайлов комиссияларнинг харакатлари низолашиш тугрисида",
    secondTitle:
      "2.2 - Маъмурий орган, фукаролар узини узи бошкариш органларининг ва...",
    thirdTitle: "2.2 - Маъмурий орган, фукаролар узини узи бошкариш органл...",
    decisionTitle: "Карор раками",
    decisionNum: "1234567890",
    decisionDateTitle: "Карор санаси",
    decisionDate: "12.03.2021",
    introForceTitle: "Карор кучга кирган сана",
    introForceDate: "12.03.2021",
    cancellationTitle: "Бекор килиш учун асос",
    cancellationBasis: "Келтирилган асос",
    administrativeTitle: "Маъмурий орган номи",
    administrative: "Маъмурий орган номи",
    signatoryTitle: "Карорни имзолаган шахс",
    signatory: "ANTONYUK SERGEY ALEKSANDROVICH",
  },
  {
    firstTitle: "10-Сайлов комиссияларнинг харакатлари низолашиш тугрисида",
    secondTitle:
      "2.2 - Маъмурий орган, фукаролар узини узи бошкариш органларининг ва...",
    thirdTitle: "2.2 - Маъмурий орган, фукаролар узини узи бошкариш органл...",
    decisionTitle: "Карор раками",
    decisionNum: "1234567890",
    decisionDateTitle: "Карор санаси",
    decisionDate: "12.03.2021",
    introForceTitle: "Карор кучга кирган сана",
    introForceDate: "12.03.2021",
    cancellationTitle: "Бекор килиш учун асос",
    cancellationBasis: "Келтирилган асос",
    administrativeTitle: "Маъмурий орган номи",
    administrative: "Маъмурий орган номи",
    signatoryTitle: "Карорни имзолаган шахс",
    signatory: "ANTONYUK SERGEY ALEKSANDROVICH",
  },
];
